name: Build tests
permissions:
  contents: read
on:
  - push
  - pull_request
env:
  COMMON_ARGS:
jobs:
  build-windows:
    strategy:
      matrix:
        configuration:
          - Debug
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: 2022
      - name: Configure project
        run: |
          mkdir build
          cmake -B build --warn-uninitialized -Werror=dev -G Ninja -DLIBICAL_DEVMODE_MEMORY_CONSISTENCY=True -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DLIBICAL_DEVMODE=True -DLIBICAL_GLIB_BUILD_DOCS=False -DLIBICAL_GLIB=False -DLIBICAL_GOBJECT_INTROSPECTION=False -DLIBICAL_GLIB_VAPI=False -DLIBICAL_BUILD_TESTING_BIGFUZZ=True
        shell: cmd
      - name: Build project
        run: cmake --build build
        shell: cmd
      - name: Test project
        run: |
          cd build
          ctest -VV
          ctest --rerun-failed --output-on-failure
        shell: cmd

  build-ubuntu:
    strategy:
      matrix:
        configuration:
          - Debug
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get -y install python3-pip xml-core libdb-dev gobject-introspection libgirepository1.0-dev valac cmake ninja-build && pip3 install --user gi-docgen
      - name: Configure project
        run: |
          mkdir build
          cmake -B build --warn-uninitialized -Werror=dev -G Ninja -DLIBICAL_DEVMODE_MEMORY_CONSISTENCY=False -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DLIBICAL_DEVMODE=True -DLIBICAL_GLIB_BUILD_DOCS=True -DLIBICAL_GLIB=True -DLIBICAL_GOBJECT_INTROSPECTION=True -DLIBICAL_GLIB_VAPI=True -DLIBICAL_GLIB_CHECK_API_FILES=True -DLIBICAL_BUILD_TESTING_BIGFUZZ=True -DLIBICAL_BUILD_VZIC=True
      - name: Build project
        run: cmake --build build
      - name: Test project
        run: cd build && (ctest --test-dir . || ctest --rerun-failed --output-on-failure)

  build-macos:
    strategy:
      matrix:
        configuration:
          - Debug
    runs-on: macos-14
    env:
      XML_CATALOG_FILES: /usr/local/etc/xml/catalog
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install pkg-config ninja glib libxml2 icu4c berkeley-db
      - name: Configure project
        run: |
          export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
          mkdir build
          cmake -B build --warn-uninitialized -Werror=dev -G Ninja -DLIBICAL_DEVMODE_MEMORY_CONSISTENCY=False -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DLIBICAL_DEVMODE=True -DLIBICAL_GLIB_BUILD_DOCS=False -DLIBICAL_GLIB=True -DLIBICAL_GOBJECT_INTROSPECTION=False -DLIBICAL_GLIB_VAPI=False -DLIBICAL_BUILD_TESTING_BIGFUZZ=True
      - name: Build project
        run: cmake --build build
      - name: Test project
        run: cd build && (ctest --test-dir . || ctest --rerun-failed --output-on-failure)
