name: Build tests
on:
  - push
  - pull_request
env:
  COMMON_ARGS:
jobs:
  build-windows:
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: 2019
      - name: Configure project
        run: |
          mkdir build
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DLIBICAL_BUILD_TESTING=True -DENABLE_GTK_DOC=False -DICAL_GLIB=False -DGOBJECT_INTROSPECTION=False -DICAL_GLIB_VAPI=False
        shell: cmd
      - name: Build project
        run: cmake --build build
        shell: cmd
      - name: Test project
        run: cd build && ctest --test-dir .
        shell: cmd

  build-ubuntu:
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get -y install gtk-doc-tools xml-core libdb-dev gobject-introspection libgirepository1.0-dev valac cmake ninja-build
      - name: Configure project
        run: |
          mkdir build
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DLIBICAL_BUILD_TESTING=True -DENABLE_GTK_DOC=True -DICAL_GLIB=True -DGOBJECT_INTROSPECTION=True -DICAL_GLIB_VAPI=True -DLIBICAL_BUILD_TESTING_BIGFUZZ=True
      - name: Build project
        run: cmake --build build
      - name: Test project
        run: cd build && ctest --test-dir .

  build-macos:
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
    runs-on: macos-13
    env:
      XML_CATALOG_FILES: /usr/local/etc/xml/catalog
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install pkg-config ninja gtk-doc glib libxml2 icu4c berkeley-db docbook docbook-xsl
      - name: Configure project
        run: |
          export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
          export XML_CATALOG_FILES=/usr/local/etc/xml/catalog
          mkdir build
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DLIBICAL_BUILD_TESTING=True -DENABLE_GTK_DOC=False -DICAL_GLIB=False -DGOBJECT_INTROSPECTION=False -DICAL_GLIB_VAPI=False -DLIBICAL_BUILD_TESTING_BIGFUZZ=True
      - name: Build project
        run: cmake --build build
      - name: Test project
        run: cd build && ctest --test-dir .
